name: GitHubKit
include: ../project.yml
targets:
  GitHubKitiOS:
    type: framework
    platform: iOS
    scheme:
      testTargets:
        - GitHubKitiOSTests
    sources: Sources/
    dependencies:
      - carthage: Client
      - carthage: Result
    settings:
      groups:
        - ios
      base:
        PRODUCT_NAME: GitHubKit
  GitHubKitiOSTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/
    dependencies:
      - target: GitHubKitiOS
      - carthage: Client
      - carthage: Result
  GitHubKitwatchOS:
    type: framework
    platform: watchOS
    sources: Sources/
    dependencies:
      - carthage: Client
      - carthage: Result
    settings:
      groups:
        - watchos
      base:
        PRODUCT_NAME: GitHubKit