name: App
include: ../project.yml
targets:
  App:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - AppTests
    sources: 
      - App.entitlements
      - Sources/
      - Info.plist
      - Resources/
    dependencies:
      - target: ShareIssue
      - framework: IssuesUI.framework
        implicit: true
      - framework: IssuesKit.framework
        implicit: true
      - framework: GitHubKit.framework
        link: false
        implicit: true
        embed: true
      - carthage: Client
      - carthage: Result
      - carthage: Client
      - carthage: Result
      - carthage: RxSwift
      - carthage: KeychainSwift
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: App.entitlements
  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - Tests/
      - Tests.plist
    dependencies:
      - target: App
      - carthage: Client
      - carthage: Result
      - carthage: RxSwift
      - carthage: KeychainSwift
      - framework: IssuesUI.framework
        implicit: true
      - framework: IssuesKit.framework
        implicit: true
      - framework: GitHubKit.framework
        link: false
        implicit: true
    settings:
      base:
        INFOPLIST_FILE: Tests.plist
  ShareIssue:
    type: app-extension.messages
    platform: iOS
    sources: 
      - path: ShareIssue/Sources/
        name: ShareIssueSources
      - ShareIssue.plist
      - path: ShareIssue/Resources
        name: ShareIssueResources
      - ShareIssue.entitlements
    settings:
      base:
        INFOPLIST_FILE: ShareIssue.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.romobos.App.ShareIssue
        CODE_SIGN_ENTITLEMENTS: ShareIssue.entitlements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    dependencies:
      - framework: IssuesUI.framework
        implicit: true
      - framework: IssuesKit.framework
        implicit: true
      - framework: GitHubKit.framework
        link: false
        implicit: true
        embed: true
      - carthage: Client
      - carthage: Result
      - carthage: Client
      - carthage: Result
      - carthage: RxSwift
      - carthage: KeychainSwift